{% set data= load_setup_py_data() %}
package:
    name: "ts-electrometer"
    version: {{ data.get('version') }}

source:
    path: ../

build:
    noarch: python
    entry_points:
        - run_electrometer = lsst.ts.electrometer.csc:execute_csc
        - command_electrometer = lsst.ts.electrometer.csc:command_csc
    script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
    requires:
        - ts-conda-build =0.4
        - ts-idl {{ idl_version }}
        - ts-salobj {{ salobj_version }}
    source_files:
        - python
        - bin
        - tests
        - pyproject.toml
    commands:
        - pytest

requirements:
    host:
        - python {{ python }}
        - pip
        - setuptools_scm
        - setuptools
    build:
        - python {{ python }}
        - setuptools_scm
        - setuptools
    run:
        - python {{ python }}
        - setuptools
        - setuptools_scm
        - ts-salobj
        - ts-tcpip
        - ts-idl
        - ts-utils
