[project]
title = "ts_electrometer"
copyright = "2015-2026 Association of Universities for Research in Astronomy, Inc. (AURA)"

[project.python]
package = "ts-electrometer"
documentation_url_key = "documentation"
github_url_key = "source_code"

[sphinx.intersphinx.projects]
pyserial = "https://pyserial.readthedocs.io/en/latest"
ts_salobj = "https://ts-salobj.lsst.io"
ts_xml = "https://ts-xml.lsst.io"
