# -------- This file is automatically generated by LSST's sconsUtils -------- #
__version__ = 'unknown'
__repo_version__ = 'unknown'
__fingerprint__ = '646a8435e0912eda6a49552011e52f867fd87bcd *'
__dependency_versions__ = {
}
__all__ = (
    '__version__',
    '__repo_version__',
    '__fingerprint__',
    '__dependency_versions__',
)
